version: '3'
services:
  gan_palhares:
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 2
              capabilities: [gpu]
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
       - user_name=gan_palhares
    container_name: gan_palhares
    image: palhares/gan_palhares
    restart: unless-stopped
    environment:
      PYTHONUNBUFFERED: 1
